In [1]:
import sys
import pandas as pd

print("Python executable:")
print(sys.executable)

print("\nPython version:")
print(sys.version)

print("\nPandas version:")
print(pd.__version__)

Python executable:
c:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\venv\Scripts\python.exe

Python version:
3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]

Pandas version:
3.0.5

In [2]:
from pathlib import Path

DATASET_PATH = Path(
    r"C:\Users\nulim\Downloads\archive (1)\r4.2"
)

print("Dataset path:")
print(DATASET_PATH)

print("\nDataset exists:", DATASET_PATH.exists())

Dataset path:
C:\Users\nulim\Downloads\archive (1)\r4.2

Dataset exists: True

In [3]:
expected_files = [
    "logon.csv",
    "email.csv",
    "file.csv",
    "http.csv",
    "device.csv",
    "psychometric.csv",
]

print("CERT R4.2 files:\n")

for filename in expected_files:
    file_path = DATASET_PATH / filename

    print(
        f"{filename:20} "
        f"Exists: {file_path.exists()}"
    )

CERT R4.2 files:

logon.csv            Exists: True
email.csv            Exists: True
file.csv             Exists: True
http.csv             Exists: True
device.csv           Exists: True
psychometric.csv     Exists: True

In [4]:
import pandas as pd

files_to_check = [
    "logon.csv",
    "email.csv",
    "file.csv",
    "http.csv",
    "device.csv",
    "psychometric.csv",
]

for filename in files_to_check:
    file_path = DATASET_PATH / filename

    print("=" * 70)
    print(f"FILE: {filename}")
    print("=" * 70)

    # Read only the first 5 rows
    sample = pd.read_csv(
        file_path,
        nrows=5
    )

    print("Columns:")
    print(sample.columns.tolist())

    print("\nSample:")
    display(sample.head())

======================================================================
FILE: logon.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'activity']

Sample:

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

======================================================================
FILE: email.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'to', 'cc', 'bcc', 'from', 'size', 'attachments', 'content']

Sample:

,id,date,user,pc,to,cc,bcc,from,size,attachments,content
0,{R3I7-S4TX96FG-8219JWFF},01/02/2010 07:11:45,LAP0338,PC-5758,Dean.Flynn.Hines@dtaa.com;Wade_Harrison@lockhe...,Nathaniel.Hunter.Heath@dtaa.com,NaN,Lynn.Adena.Pratt@dtaa.com,25830,0,middle f2 systems 4 july techniques powerful d...
1,{R0R9-E4GL59IK-2907OSWJ},01/02/2010 07:12:16,MOH0273,PC-6699,Odonnell-Gage@bellsouth.net,NaN,NaN,MOH68@optonline.net,29942,0,the breaking called allied reservations former...
2,{G2B2-A8XY58CP-2847ZJZL},01/02/2010 07:13:00,LAP0338,PC-5758,Penelope_Colon@netzero.com,NaN,NaN,Lynn_A_Pratt@earthlink.net,28780,0,slowly this uncinus winter beneath addition ex...
3,{A3A9-F4TH89AA-8318GFGK},01/02/2010 07:13:17,LAP0338,PC-5758,Judith_Hayden@comcast.net,NaN,NaN,Lynn_A_Pratt@earthlink.net,21907,0,400 other difficult land cirrocumulus powered ...
4,{E8B7-C8FZ88UF-2946RUQQ},01/02/2010 07:13:28,MOH0273,PC-6699,Bond-Raymond@verizon.net;Alea_Ferrell@msn.com;...,NaN,Odonnell-Gage@bellsouth.net,MOH68@optonline.net,17319,0,this kmh october holliswood number advised unu...

======================================================================
FILE: file.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'filename', 'content']

Sample:

,id,date,user,pc,filename,content
0,{L9G8-J9QE34VM-2834VDPB},01/02/2010 07:23:14,MOH0273,PC-6699,EYPC9Y08.doc,D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...
1,{H0W6-L4FG38XG-9897XTEN},01/02/2010 07:26:19,MOH0273,PC-6699,N3LTSU3O.pdf,25-50-44-46-2D carpenters 25 landed strait dis...
2,{M3Z0-O2KK89OX-5716MBIM},01/02/2010 08:12:03,HPH0075,PC-2417,D3D3WC9W.doc,D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...
3,{E1I4-S4QS61TG-3652YHKR},01/02/2010 08:17:00,HPH0075,PC-2417,QCSW62YS.doc,D0-CF-11-E0-A1-B1-1A-E1 becoming period begin ...
4,{D4R7-E7JL45UX-0067XALT},01/02/2010 08:24:57,HSB0196,PC-8001,AU75JV6U.jpg,FF-D8

======================================================================
FILE: http.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'url', 'content']

Sample:

,id,date,user,pc,url,content
0,{V1Y4-S2IR20QU-6154HFXJ},01/02/2010 06:55:16,LRR0148,PC-4275,http://msn.com/The_Human_Centipede_First_Seque...,remain representatives consensus concert altho...
1,{Q5R1-T3EF87UE-2395RWZS},01/02/2010 07:00:13,NGF0157,PC-6056,http://urbanspoon.com/Plunketts_Creek_Loyalsoc...,festival off northwards than congestion partne...
2,{X9O1-O0XW52VO-5806RPHG},01/02/2010 07:03:46,NGF0157,PC-6056,http://aa.com/Rhodocene/rhodocenium/fhaavatqrf...,long away reorganized baldwin seth business 18...
3,{G5S8-U5OG04TE-5299CCTU},01/02/2010 07:05:26,IRM0931,PC-7188,http://groupon.com/Leonhard_Euler/leonhard/tne...,among german schwein experimental becomes prev...
4,{L0R4-A9DH29VP-4553AUWM},01/02/2010 07:05:52,IRM0931,PC-7188,http://flickr.com/Inauguration_of_Barack_Obama...,kate criteria j 2008 highest 12 include books ...

======================================================================
FILE: device.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'activity']

Sample:

                         id                 date     user       pc    activity
0  {J1S3-L9UU75BQ-7790ATPL}  01/02/2010 07:21:06  MOH0273  PC-6699     Connect
1  {N7B5-Y7BB27SI-2946PUJK}  01/02/2010 07:37:41  MOH0273  PC-6699  Disconnect
2  {U1V9-Z7XT67KV-5649MYHI}  01/02/2010 07:59:11  HPH0075  PC-2417     Connect
3  {H0Z7-E6GB57XZ-1603MOXD}  01/02/2010 07:59:49  IIW0249  PC-0843     Connect
4  {L7P2-G4PX02RX-7999GYOY}  01/02/2010 08:04:26  IIW0249  PC-0843  Disconnect

======================================================================
FILE: psychometric.csv
======================================================================
Columns:
['employee_name', 'user_id', 'O', 'C', 'E', 'A', 'N']

Sample:

             employee_name  user_id   O   C   E   A   N
0         Calvin Edan Love  CEL0561  40  39  36  19  40
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25

In [5]:
import pandas as pd

files_to_check = [
    "logon.csv",
    "email.csv",
    "file.csv",
    "http.csv",
    "device.csv",
    "psychometric.csv",
]

for filename in files_to_check:
    file_path = DATASET_PATH / filename

    print("=" * 70)
    print(f"FILE: {filename}")
    print("=" * 70)

    # Read only the first 5 rows
    sample = pd.read_csv(
        file_path,
        nrows=5
    )

    print("Columns:")
    print(sample.columns.tolist())

    print("\nSample:")
    display(sample.head())

======================================================================
FILE: logon.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'activity']

Sample:

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

======================================================================
FILE: email.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'to', 'cc', 'bcc', 'from', 'size', 'attachments', 'content']

Sample:

,id,date,user,pc,to,cc,bcc,from,size,attachments,content
0,{R3I7-S4TX96FG-8219JWFF},01/02/2010 07:11:45,LAP0338,PC-5758,Dean.Flynn.Hines@dtaa.com;Wade_Harrison@lockhe...,Nathaniel.Hunter.Heath@dtaa.com,NaN,Lynn.Adena.Pratt@dtaa.com,25830,0,middle f2 systems 4 july techniques powerful d...
1,{R0R9-E4GL59IK-2907OSWJ},01/02/2010 07:12:16,MOH0273,PC-6699,Odonnell-Gage@bellsouth.net,NaN,NaN,MOH68@optonline.net,29942,0,the breaking called allied reservations former...
2,{G2B2-A8XY58CP-2847ZJZL},01/02/2010 07:13:00,LAP0338,PC-5758,Penelope_Colon@netzero.com,NaN,NaN,Lynn_A_Pratt@earthlink.net,28780,0,slowly this uncinus winter beneath addition ex...
3,{A3A9-F4TH89AA-8318GFGK},01/02/2010 07:13:17,LAP0338,PC-5758,Judith_Hayden@comcast.net,NaN,NaN,Lynn_A_Pratt@earthlink.net,21907,0,400 other difficult land cirrocumulus powered ...
4,{E8B7-C8FZ88UF-2946RUQQ},01/02/2010 07:13:28,MOH0273,PC-6699,Bond-Raymond@verizon.net;Alea_Ferrell@msn.com;...,NaN,Odonnell-Gage@bellsouth.net,MOH68@optonline.net,17319,0,this kmh october holliswood number advised unu...

======================================================================
FILE: file.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'filename', 'content']

Sample:

,id,date,user,pc,filename,content
0,{L9G8-J9QE34VM-2834VDPB},01/02/2010 07:23:14,MOH0273,PC-6699,EYPC9Y08.doc,D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...
1,{H0W6-L4FG38XG-9897XTEN},01/02/2010 07:26:19,MOH0273,PC-6699,N3LTSU3O.pdf,25-50-44-46-2D carpenters 25 landed strait dis...
2,{M3Z0-O2KK89OX-5716MBIM},01/02/2010 08:12:03,HPH0075,PC-2417,D3D3WC9W.doc,D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...
3,{E1I4-S4QS61TG-3652YHKR},01/02/2010 08:17:00,HPH0075,PC-2417,QCSW62YS.doc,D0-CF-11-E0-A1-B1-1A-E1 becoming period begin ...
4,{D4R7-E7JL45UX-0067XALT},01/02/2010 08:24:57,HSB0196,PC-8001,AU75JV6U.jpg,FF-D8

======================================================================
FILE: http.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'url', 'content']

Sample:

,id,date,user,pc,url,content
0,{V1Y4-S2IR20QU-6154HFXJ},01/02/2010 06:55:16,LRR0148,PC-4275,http://msn.com/The_Human_Centipede_First_Seque...,remain representatives consensus concert altho...
1,{Q5R1-T3EF87UE-2395RWZS},01/02/2010 07:00:13,NGF0157,PC-6056,http://urbanspoon.com/Plunketts_Creek_Loyalsoc...,festival off northwards than congestion partne...
2,{X9O1-O0XW52VO-5806RPHG},01/02/2010 07:03:46,NGF0157,PC-6056,http://aa.com/Rhodocene/rhodocenium/fhaavatqrf...,long away reorganized baldwin seth business 18...
3,{G5S8-U5OG04TE-5299CCTU},01/02/2010 07:05:26,IRM0931,PC-7188,http://groupon.com/Leonhard_Euler/leonhard/tne...,among german schwein experimental becomes prev...
4,{L0R4-A9DH29VP-4553AUWM},01/02/2010 07:05:52,IRM0931,PC-7188,http://flickr.com/Inauguration_of_Barack_Obama...,kate criteria j 2008 highest 12 include books ...

======================================================================
FILE: device.csv
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'activity']

Sample:

                         id                 date     user       pc    activity
0  {J1S3-L9UU75BQ-7790ATPL}  01/02/2010 07:21:06  MOH0273  PC-6699     Connect
1  {N7B5-Y7BB27SI-2946PUJK}  01/02/2010 07:37:41  MOH0273  PC-6699  Disconnect
2  {U1V9-Z7XT67KV-5649MYHI}  01/02/2010 07:59:11  HPH0075  PC-2417     Connect
3  {H0Z7-E6GB57XZ-1603MOXD}  01/02/2010 07:59:49  IIW0249  PC-0843     Connect
4  {L7P2-G4PX02RX-7999GYOY}  01/02/2010 08:04:26  IIW0249  PC-0843  Disconnect

======================================================================
FILE: psychometric.csv
======================================================================
Columns:
['employee_name', 'user_id', 'O', 'C', 'E', 'A', 'N']

Sample:

             employee_name  user_id   O   C   E   A   N
0         Calvin Edan Love  CEL0561  40  39  36  19  40
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25

In [6]:
for filename in files_to_check:
    file_path = DATASET_PATH / filename

    size_mb = file_path.stat().st_size / (1024 ** 2)

    print(f"{filename:20} {size_mb:,.2f} MB")

logon.csv            55.80 MB
email.csv            1,299.00 MB
file.csv             184.11 MB
http.csv             13,862.86 MB
device.csv           27.64 MB
psychometric.csv     0.04 MB

In [7]:
import pandas as pd
import time

files_to_count = [
    "logon.csv",
    "email.csv",
    "file.csv",
    "http.csv",
    "device.csv",
    "psychometric.csv",
]

row_counts = {}

for filename in files_to_count:
    file_path = DATASET_PATH / filename

    print(f"\nCounting rows: {filename}")
    start_time = time.time()

    count = 0

    for chunk in pd.read_csv(
        file_path,
        chunksize=100_000,
        usecols=[0]
    ):
        count += len(chunk)

    row_counts[filename] = count

    elapsed = time.time() - start_time

    print(f"Rows: {count:,}")
    print(f"Time: {elapsed:.2f} seconds")
  
print("\n" + "=" * 60)
print("FINAL ROW COUNTS")
print("=" * 60)

for filename, count in row_counts.items():
    print(f"{filename:20} {count:,}")

Counting rows: logon.csv
Rows: 854,859
Time: 1.76 seconds

Counting rows: email.csv
Rows: 2,629,979
Time: 26.49 seconds

Counting rows: file.csv
Rows: 445,581
Time: 3.98 seconds

Counting rows: http.csv
Rows: 28,434,423
Time: 286.74 seconds

Counting rows: device.csv
Rows: 405,380
Time: 1.04 seconds

Counting rows: psychometric.csv
Rows: 1,000
Time: 0.01 seconds

============================================================
FINAL ROW COUNTS
============================================================
logon.csv            854,859
email.csv            2,629,979
file.csv             445,581
http.csv             28,434,423
device.csv           405,380
psychometric.csv     1,000

In [8]:
import pandas as pd
from collections import Counter

# ---------------------------------------------------------
# CERT R4.2 Behavioral Profile
# ---------------------------------------------------------

activity_files = {
    "logon": "logon.csv",
    "email": "email.csv",
    "file": "file.csv",
    "http": "http.csv",
    "device": "device.csv",
}

for name, filename in activity_files.items():

    file_path = DATASET_PATH / filename

    print("\n" + "=" * 70)
    print(f"{name.upper()} DATASET")
    print("=" * 70)

    unique_users = set()
    unique_pcs = set()
    activity_counts = Counter()

    min_date = None
    max_date = None

    for chunk in pd.read_csv(
        file_path,
        chunksize=100_000,
        usecols=["date", "user", "pc"] +
                (["activity"] if name in ["logon", "device"] else [])
    ):

        # -----------------------------
        # Users
        # -----------------------------
        unique_users.update(
            chunk["user"].dropna().astype(str).unique()
        )

        # -----------------------------
        # PCs
        # -----------------------------
        unique_pcs.update(
            chunk["pc"].dropna().astype(str).unique()
        )

        # -----------------------------
        # Activity types
        # -----------------------------
        if "activity" in chunk.columns:
            activity_counts.update(
                chunk["activity"]
                .dropna()
                .astype(str)
                .value_counts()
                .to_dict()
            )

        # -----------------------------
        # Dates
        # -----------------------------
        dates = pd.to_datetime(
            chunk["date"],
            errors="coerce"
        )

        chunk_min = dates.min()
        chunk_max = dates.max()

        if pd.notna(chunk_min):
            if min_date is None or chunk_min < min_date:
                min_date = chunk_min

        if pd.notna(chunk_max):
            if max_date is None or chunk_max > max_date:
                max_date = chunk_max

    print(f"Unique users : {len(unique_users):,}")
    print(f"Unique PCs   : {len(unique_pcs):,}")
    print(f"Start date   : {min_date}")
    print(f"End date     : {max_date}")

    if activity_counts:
        print("\nActivity types:")
        for activity, count in activity_counts.items():
            print(f"  {activity:15} {count:,}")

======================================================================
LOGON DATASET
======================================================================
Unique users : 1,000
Unique PCs   : 1,003
Start date   : 2010-01-02 06:49:00
End date     : 2011-05-17 06:43:35

Activity types:
  Logon           470,591
  Logoff          384,268

======================================================================
EMAIL DATASET
======================================================================
Unique users : 1,000
Unique PCs   : 1,000
Start date   : 2010-01-02 07:11:45
End date     : 2011-05-16 21:16:26

======================================================================
FILE DATASET
======================================================================
Unique users : 264
Unique PCs   : 956
Start date   : 2010-01-02 07:23:14
End date     : 2011-05-16 23:22:34

======================================================================
HTTP DATASET
======================================================================
Unique users : 1,000
Unique PCs   : 1,000
Start date   : 2010-01-02 06:55:16
End date     : 2011-05-16 21:23:10

======================================================================
DEVICE DATASET
======================================================================
Unique users : 265
Unique PCs   : 971
Start date   : 2010-01-02 07:21:06
End date     : 2011-05-16 23:22:34

Activity types:
  Connect         203,339
  Disconnect      202,041

In [9]:
# Print only the important summary information
# so the output is not truncated.

for name, filename in activity_files.items():

    file_path = DATASET_PATH / filename

    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)

    users = set()

    for chunk in pd.read_csv(
        file_path,
        chunksize=100_000,
        usecols=["user"]
    ):
        users.update(
            chunk["user"].dropna().astype(str).unique()
        )

    print("Unique users:", len(users))

============================================================
LOGON
============================================================
Unique users: 1000

============================================================
EMAIL
============================================================
Unique users: 1000

============================================================
FILE
============================================================
Unique users: 264

============================================================
HTTP
============================================================
Unique users: 1000

============================================================
DEVICE
============================================================
Unique users: 265

In [10]:
# Inspect representative values from each dataset

inspection_files = {
    "logon": "logon.csv",
    "email": "email.csv",
    "file": "file.csv",
    "http": "http.csv",
    "device": "device.csv",
}

for name, filename in inspection_files.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)

    file_path = DATASET_PATH / filename

    sample = pd.read_csv(
        file_path,
        nrows=10
    )

    print("Columns:")
    print(sample.columns.tolist())

    print("\nFirst 3 rows:")
    display(sample.head(3))

======================================================================
LOGON
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'activity']

First 3 rows:

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon

======================================================================
EMAIL
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'to', 'cc', 'bcc', 'from', 'size', 'attachments', 'content']

First 3 rows:

,id,date,user,pc,to,cc,bcc,from,size,attachments,content
0,{R3I7-S4TX96FG-8219JWFF},01/02/2010 07:11:45,LAP0338,PC-5758,Dean.Flynn.Hines@dtaa.com;Wade_Harrison@lockhe...,Nathaniel.Hunter.Heath@dtaa.com,NaN,Lynn.Adena.Pratt@dtaa.com,25830,0,middle f2 systems 4 july techniques powerful d...
1,{R0R9-E4GL59IK-2907OSWJ},01/02/2010 07:12:16,MOH0273,PC-6699,Odonnell-Gage@bellsouth.net,NaN,NaN,MOH68@optonline.net,29942,0,the breaking called allied reservations former...
2,{G2B2-A8XY58CP-2847ZJZL},01/02/2010 07:13:00,LAP0338,PC-5758,Penelope_Colon@netzero.com,NaN,NaN,Lynn_A_Pratt@earthlink.net,28780,0,slowly this uncinus winter beneath addition ex...

======================================================================
FILE
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'filename', 'content']

First 3 rows:

,id,date,user,pc,filename,content
0,{L9G8-J9QE34VM-2834VDPB},01/02/2010 07:23:14,MOH0273,PC-6699,EYPC9Y08.doc,D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...
1,{H0W6-L4FG38XG-9897XTEN},01/02/2010 07:26:19,MOH0273,PC-6699,N3LTSU3O.pdf,25-50-44-46-2D carpenters 25 landed strait dis...
2,{M3Z0-O2KK89OX-5716MBIM},01/02/2010 08:12:03,HPH0075,PC-2417,D3D3WC9W.doc,D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...

======================================================================
HTTP
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'url', 'content']

First 3 rows:

,id,date,user,pc,url,content
0,{V1Y4-S2IR20QU-6154HFXJ},01/02/2010 06:55:16,LRR0148,PC-4275,http://msn.com/The_Human_Centipede_First_Seque...,remain representatives consensus concert altho...
1,{Q5R1-T3EF87UE-2395RWZS},01/02/2010 07:00:13,NGF0157,PC-6056,http://urbanspoon.com/Plunketts_Creek_Loyalsoc...,festival off northwards than congestion partne...
2,{X9O1-O0XW52VO-5806RPHG},01/02/2010 07:03:46,NGF0157,PC-6056,http://aa.com/Rhodocene/rhodocenium/fhaavatqrf...,long away reorganized baldwin seth business 18...

======================================================================
DEVICE
======================================================================
Columns:
['id', 'date', 'user', 'pc', 'activity']

First 3 rows:

                         id                 date     user       pc    activity
0  {J1S3-L9UU75BQ-7790ATPL}  01/02/2010 07:21:06  MOH0273  PC-6699     Connect
1  {N7B5-Y7BB27SI-2946PUJK}  01/02/2010 07:37:41  MOH0273  PC-6699  Disconnect
2  {U1V9-Z7XT67KV-5649MYHI}  01/02/2010 07:59:11  HPH0075  PC-2417     Connect

In [11]:
logon_sample = pd.read_csv(
    DATASET_PATH / "logon.csv",
    nrows=10
)

display(logon_sample)

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon
5  {S6P1-M4MK04BB-0722IITW}  01/02/2010 07:07:00  LAP0338  PC-5758    Logon
6  {M6O6-F9UU11TJ-2166YVFU}  01/02/2010 07:08:00  MHH0180  PC-9822    Logon
7  {D0P1-U5IU49QG-5472TMLI}  01/02/2010 07:08:00  NOB0181  PC-3446    Logon
8  {F9K3-Q1PD92IU-5821IGXW}  01/02/2010 07:13:00  AHC0142  PC-8893    Logon
9  {S9A0-A3DP89HG-6719JORU}  01/02/2010 07:14:00  CTR0341  PC-6184    Logon

In [12]:
print(logon_sample.dtypes)

id          str
date        str
user        str
pc          str
activity    str
dtype: object

In [13]:
print(logon_sample["activity"].value_counts())

activity
Logon    10
Name: count, dtype: int64

In [14]:
import pandas as pd

logon_features = {}

for chunk in pd.read_csv(
    DATASET_PATH / "logon.csv",
    chunksize=100_000,
    usecols=["date", "user", "pc", "activity"],
    parse_dates=["date"]
):
    # Remove records without a user
    chunk = chunk.dropna(subset=["user"])

    # Convert user to string consistently
    chunk["user"] = chunk["user"].astype(str)

    # Identify logon/logoff
    is_logon = chunk["activity"].eq("Logon")
    is_logoff = chunk["activity"].eq("Logoff")

    # After-hours:
    # before 08:00 OR at/after 18:00
    hour = chunk["date"].dt.hour
    after_hours = (hour < 8) | (hour >= 18)

    # Aggregate this chunk by user
    chunk_features = (
        chunk.assign(
            logon_count=is_logon.astype(int),
            logoff_count=is_logoff.astype(int),
            after_hours_logon=(
                is_logon & after_hours
            ).astype(int),
            after_hours_logoff=(
                is_logoff & after_hours
            ).astype(int)
        )
        .groupby("user")
        .agg(
            logon_count=("logon_count", "sum"),
            logoff_count=("logoff_count", "sum"),
            after_hours_logon_count=(
                "after_hours_logon",
                "sum"
            ),
            after_hours_logoff_count=(
                "after_hours_logoff",
                "sum"
            ),
            unique_pc_count=("pc", "nunique")
        )
    )

    # Merge this chunk into our running result
    for user, row in chunk_features.iterrows():

        if user not in logon_features:
            logon_features[user] = row.to_dict()
        else:
            logon_features[user]["logon_count"] += row["logon_count"]
            logon_features[user]["logoff_count"] += row["logoff_count"]
            logon_features[user]["after_hours_logon_count"] += (
                row["after_hours_logon_count"]
            )
            logon_features[user]["after_hours_logoff_count"] += (
                row["after_hours_logoff_count"]
            )

            # unique PC needs a proper set-based calculation,
            # so we handle it separately below.

In [15]:
print("Logon processing completed.")
print("Number of users:", len(logon_features))

Logon processing completed.
Number of users: 1000

In [16]:
logon_features_df = pd.DataFrame.from_dict(
    logon_features,
    orient="index"
)

logon_features_df.index.name = "user"

display(logon_features_df.head(10))
print("Shape:", logon_features_df.shape)

,logon_count,logoff_count,after_hours_logon_count,after_hours_logoff_count,unique_pc_count
user,,,,,
AAE0190,346,346,0,346,1
AAF0535,164,164,0,0,1
AAF0791,346,346,0,0,1
AAL0706,346,346,346,0,1
AAM0658,229,229,5,229,1
AAN0823,346,346,0,346,1
AAS0442,86,50,22,0,1
AAV0450,346,346,159,186,1
AAW0353,346,346,165,232,1
ABC0174,533,296,296,0,1

Shape: (1000, 5)

In [17]:
print("Logon processing completed.")
print("Number of users:", len(logon_features))

Logon processing completed.
Number of users: 1000

In [18]:
logon_features_df = pd.DataFrame.from_dict(
    logon_features,
    orient="index"
)

logon_features_df.index.name = "user"

display(logon_features_df.head(10))

print("Shape:", logon_features_df.shape)

,logon_count,logoff_count,after_hours_logon_count,after_hours_logoff_count,unique_pc_count
user,,,,,
AAE0190,346,346,0,346,1
AAF0535,164,164,0,0,1
AAF0791,346,346,0,0,1
AAL0706,346,346,346,0,1
AAM0658,229,229,5,229,1
AAN0823,346,346,0,346,1
AAS0442,86,50,22,0,1
AAV0450,346,346,159,186,1
AAW0353,346,346,165,232,1
ABC0174,533,296,296,0,1

Shape: (1000, 5)

In [19]:
# ============================================================
# EMAIL FEATURE ENGINEERING
# ============================================================

from collections import defaultdict

email_counts = defaultdict(int)
email_attachment_count = defaultdict(int)
email_total_attachments = defaultdict(int)
email_total_size = defaultdict(int)
email_recipients = defaultdict(set)

email_file = DATASET_PATH / "email.csv"

for chunk in pd.read_csv(
    email_file,
    chunksize=100_000,
    usecols=[
        "user",
        "to",
        "cc",
        "bcc",
        "size",
        "attachments"
    ]
):
    # Remove rows without a user
    chunk = chunk.dropna(subset=["user"])

    chunk["user"] = chunk["user"].astype(str)

    # --------------------------------------------------------
    # Email count
    # --------------------------------------------------------
    counts = chunk["user"].value_counts()

    for user, count in counts.items():
        email_counts[user] += int(count)

    # --------------------------------------------------------
    # Attachments
    # --------------------------------------------------------
    chunk["attachments"] = pd.to_numeric(
        chunk["attachments"],
        errors="coerce"
    ).fillna(0)

    attachment_rows = chunk["attachments"] > 0

    attachment_counts = (
        chunk.loc[attachment_rows, "user"]
        .value_counts()
    )

    for user, count in attachment_counts.items():
        email_attachment_count[user] += int(count)

    attachment_totals = (
        chunk.groupby("user")["attachments"]
        .sum()
    )

    for user, total in attachment_totals.items():
        email_total_attachments[user] += int(total)

    # --------------------------------------------------------
    # Email size
    # --------------------------------------------------------
    chunk["size"] = pd.to_numeric(
        chunk["size"],
        errors="coerce"
    ).fillna(0)

    size_totals = (
        chunk.groupby("user")["size"]
        .sum()
    )

    for user, total in size_totals.items():
        email_total_size[user] += int(total)

    # --------------------------------------------------------
    # Recipients
    # --------------------------------------------------------
    for column in ["to", "cc", "bcc"]:

        recipients = chunk[["user", column]].dropna()

        for user, recipient in zip(
            recipients["user"],
            recipients[column]
        ):
            email_recipients[user].add(
                str(recipient)
            )

print("Email processing completed.")
print("Users found:", len(email_counts))

Email processing completed.
Users found: 1000

In [20]:
email_features_df = pd.DataFrame({
    "user": list(email_counts.keys()),
    "email_count": [
        email_counts[user]
        for user in email_counts
    ],
    "emails_with_attachments": [
        email_attachment_count[user]
        for user in email_counts
    ],
    "total_attachments": [
        email_total_attachments[user]
        for user in email_counts
    ],
    "total_email_size": [
        email_total_size[user]
        for user in email_counts
    ],
    "unique_recipients": [
        len(email_recipients[user])
        for user in email_counts
    ]
})

display(email_features_df.head(10))
print("Shape:", email_features_df.shape)

,user,email_count,emails_with_attachments,total_attachments,total_email_size,unique_recipients
0,MSS0001,12034,1206,1994,361399921,3474
1,HTH0007,9116,893,1458,273863256,3450
2,KWC0004,8997,897,1811,268029239,3335
3,KBP0008,9145,2775,4575,273685979,3343
4,TVS0006,8994,3636,7259,269761656,3402
5,HCS0003,9097,3659,7372,274810589,3738
6,BTW0005,8950,3593,5972,268955836,3275
7,HPH0075,7435,2281,4528,222965777,3645
8,DLM0051,7573,2260,4050,226854809,3091
9,ATE0869,7519,2298,4531,225221206,4022

Shape: (1000, 6)

In [21]:
print("Email feature shape:", email_features_df.shape)

print("\nMissing values:")
print(email_features_df.isna().sum())

print("\nBasic statistics:")
display(email_features_df.describe())

Email feature shape: (1000, 6)

Missing values:
user                       0
email_count                0
emails_with_attachments    0
total_attachments          0
total_email_size           0
unique_recipients          0
dtype: int64

Basic statistics:

,email_count,emails_with_attachments,total_attachments,total_email_size,unique_recipients
count,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000
mean,2629.979000,563.296000,1061.449000,7.887917e+07,1280.075000
std,1830.294016,596.407346,1116.430763,5.488427e+07,824.367155
min,34.000000,0.000000,0.000000,1.062576e+06,42.000000
25%,1001.000000,67.000000,126.500000,2.996167e+07,621.750000
50%,3002.000000,387.000000,711.000000,8.992354e+07,1350.500000
75%,3693.250000,935.250000,1790.000000,1.110407e+08,1708.000000
max,12034.000000,3659.000000,7372.000000,3.613999e+08,4022.000000

In [22]:
print(
    "Aggregated email count:",
    email_features_df["email_count"].sum()
)

print(
    "Expected email rows:",
    2_629_979
)

Aggregated email count: 2629979
Expected email rows: 2629979

In [23]:
print("Aggregated email count:",
      email_features_df["email_count"].sum())

print("Expected email rows:",
      2_629_979)

print("\nMissing values:")
print(email_features_df.isna().sum())

Aggregated email count: 2629979
Expected email rows: 2629979

Missing values:
user                       0
email_count                0
emails_with_attachments    0
total_attachments          0
total_email_size           0
unique_recipients          0
dtype: int64

In [24]:
# ============================================================
# FILE FEATURE ENGINEERING
# ============================================================

from collections import defaultdict

file_activity_count = defaultdict(int)
file_names = defaultdict(set)
file_pcs = defaultdict(set)

file_path = DATASET_PATH / "file.csv"

for chunk in pd.read_csv(
    file_path,
    chunksize=100_000,
    usecols=["user", "pc", "filename"]
):
    # Remove records without a user
    chunk = chunk.dropna(subset=["user"])

    chunk["user"] = chunk["user"].astype(str)

    # --------------------------------------------------------
    # Total file activity
    # --------------------------------------------------------
    counts = chunk["user"].value_counts()

    for user, count in counts.items():
        file_activity_count[user] += int(count)

    # --------------------------------------------------------
    # Unique filenames
    # --------------------------------------------------------
    filename_rows = chunk.dropna(subset=["filename"])

    for user, filename in zip(
        filename_rows["user"],
        filename_rows["filename"]
    ):
        file_names[user].add(str(filename))

    # --------------------------------------------------------
    # Unique PCs
    # --------------------------------------------------------
    pc_rows = chunk.dropna(subset=["pc"])

    for user, pc in zip(
        pc_rows["user"],
        pc_rows["pc"]
    ):
        file_pcs[user].add(str(pc))

print("File processing completed.")
print("Users found:", len(file_activity_count))

File processing completed.
Users found: 264

In [25]:
file_features_df = pd.DataFrame({
    "user": list(file_activity_count.keys()),

    "file_activity_count": [
        file_activity_count[user]
        for user in file_activity_count
    ],

    "unique_files": [
        len(file_names[user])
        for user in file_activity_count
    ],

    "unique_file_pcs": [
        len(file_pcs[user])
        for user in file_activity_count
    ]
})

display(file_features_df.head(10))

print("Shape:", file_features_df.shape)

      user  file_activity_count  unique_files  unique_file_pcs
0  HSB0196                11627         11627                1
1  AJF0370                11053         11053              417
2  LBH0942                10889         10889                1
3  MPM0220                 6689          6689              244
4  DLM0051                10673         10673                1
5  MOH0273                 9306          9306                1
6  HPH0075                 9323          9323                1
7  DBB0384                 8543          8543                1
8  QRM0739                 8401          8401                1
9  SAA0999                 8468          8468                1

Shape: (264, 4)

In [26]:
print(
    "Aggregated file activity:",
    file_features_df["file_activity_count"].sum()
)

print(
    "Expected file rows:",
    445_581
)

print("\nMissing values:")
print(file_features_df.isna().sum())

Aggregated file activity: 445581
Expected file rows: 445581

Missing values:
user                   0
file_activity_count    0
unique_files           0
unique_file_pcs        0
dtype: int64

In [27]:
print(
    "Aggregated file activity:",
    file_features_df["file_activity_count"].sum()
)

print(
    "Expected file rows:",
    445_581
)

print("\nMissing values:")
print(file_features_df.isna().sum())

Aggregated file activity: 445581
Expected file rows: 445581

Missing values:
user                   0
file_activity_count    0
unique_files           0
unique_file_pcs        0
dtype: int64

In [28]:
http_sample = pd.read_csv(
    DATASET_PATH / "http.csv",
    nrows=5
)

print("HTTP columns:")
print(http_sample.columns.tolist())

display(http_sample)

HTTP columns:
['id', 'date', 'user', 'pc', 'url', 'content']

,id,date,user,pc,url,content
0,{V1Y4-S2IR20QU-6154HFXJ},01/02/2010 06:55:16,LRR0148,PC-4275,http://msn.com/The_Human_Centipede_First_Seque...,remain representatives consensus concert altho...
1,{Q5R1-T3EF87UE-2395RWZS},01/02/2010 07:00:13,NGF0157,PC-6056,http://urbanspoon.com/Plunketts_Creek_Loyalsoc...,festival off northwards than congestion partne...
2,{X9O1-O0XW52VO-5806RPHG},01/02/2010 07:03:46,NGF0157,PC-6056,http://aa.com/Rhodocene/rhodocenium/fhaavatqrf...,long away reorganized baldwin seth business 18...
3,{G5S8-U5OG04TE-5299CCTU},01/02/2010 07:05:26,IRM0931,PC-7188,http://groupon.com/Leonhard_Euler/leonhard/tne...,among german schwein experimental becomes prev...
4,{L0R4-A9DH29VP-4553AUWM},01/02/2010 07:05:52,IRM0931,PC-7188,http://flickr.com/Inauguration_of_Barack_Obama...,kate criteria j 2008 highest 12 include books ...

In [29]:
# ============================================================
# HTTP FEATURE ENGINEERING
# ============================================================

from collections import defaultdict
from urllib.parse import urlparse

http_request_count = defaultdict(int)
http_pcs = defaultdict(set)
http_domains = defaultdict(set)

http_file = DATASET_PATH / "http.csv"

for chunk_number, chunk in enumerate(
    pd.read_csv(
        http_file,
        chunksize=100_000,
        usecols=["user", "pc", "url"]
    ),
    start=1
):

    # Remove records without user
    chunk = chunk.dropna(subset=["user"])
    chunk["user"] = chunk["user"].astype(str)

    # --------------------------------------------------------
    # HTTP request count
    # --------------------------------------------------------
    counts = chunk["user"].value_counts()

    for user, count in counts.items():
        http_request_count[user] += int(count)

    # --------------------------------------------------------
    # Unique PCs
    # --------------------------------------------------------
    pc_rows = chunk.dropna(subset=["pc"])

    for user, pc in zip(
        pc_rows["user"],
        pc_rows["pc"]
    ):
        http_pcs[user].add(str(pc))

    # --------------------------------------------------------
    # Extract domains instead of storing complete URLs
    # --------------------------------------------------------
    url_rows = chunk.dropna(subset=["url"])

    for user, url in zip(
        url_rows["user"],
        url_rows["url"]
    ):
        try:
            url_string = str(url)

            # Add scheme if missing
            if not url_string.startswith(
                ("http://", "https://")
            ):
                url_string = "http://" + url_string

            domain = urlparse(
                url_string
            ).netloc.lower()

            if domain:
                http_domains[user].add(domain)

        except Exception:
            continue

    if chunk_number % 25 == 0:
        print(
            f"Processed approximately "
            f"{chunk_number * 100_000:,} rows..."
        )

print("\nHTTP processing completed.")
print("Users found:", len(http_request_count))

Processed approximately 2,500,000 rows...
Processed approximately 5,000,000 rows...
Processed approximately 7,500,000 rows...
Processed approximately 10,000,000 rows...
Processed approximately 12,500,000 rows...
Processed approximately 15,000,000 rows...
Processed approximately 17,500,000 rows...
Processed approximately 20,000,000 rows...
Processed approximately 22,500,000 rows...
Processed approximately 25,000,000 rows...
Processed approximately 27,500,000 rows...

HTTP processing completed.
Users found: 1000

In [30]:
# ============================================================
# HTTP FEATURE ENGINEERING
# ============================================================

from collections import defaultdict
from urllib.parse import urlparse

http_request_count = defaultdict(int)
http_pcs = defaultdict(set)
http_domains = defaultdict(set)

http_file = DATASET_PATH / "http.csv"

for chunk_number, chunk in enumerate(
    pd.read_csv(
        http_file,
        chunksize=100_000,
        usecols=["user", "pc", "url"]
    ),
    start=1
):

    # Remove records without user
    chunk = chunk.dropna(subset=["user"])
    chunk["user"] = chunk["user"].astype(str)

    # --------------------------------------------------------
    # HTTP request count
    # --------------------------------------------------------
    counts = chunk["user"].value_counts()

    for user, count in counts.items():
        http_request_count[user] += int(count)

    # --------------------------------------------------------
    # Unique PCs
    # --------------------------------------------------------
    pc_rows = chunk.dropna(subset=["pc"])

    for user, pc in zip(
        pc_rows["user"],
        pc_rows["pc"]
    ):
        http_pcs[user].add(str(pc))

    # --------------------------------------------------------
    # Extract domains instead of storing complete URLs
    # --------------------------------------------------------
    url_rows = chunk.dropna(subset=["url"])

    for user, url in zip(
        url_rows["user"],
        url_rows["url"]
    ):
        try:
            url_string = str(url)

            # Add scheme if missing
            if not url_string.startswith(
                ("http://", "https://")
            ):
                url_string = "http://" + url_string

            domain = urlparse(
                url_string
            ).netloc.lower()

            if domain:
                http_domains[user].add(domain)

        except Exception:
            continue

    if chunk_number % 25 == 0:
        print(
            f"Processed approximately "
            f"{chunk_number * 100_000:,} rows..."
        )

print("\nHTTP processing completed.")
print("Users found:", len(http_request_count))

Processed approximately 2,500,000 rows...
Processed approximately 5,000,000 rows...
Processed approximately 7,500,000 rows...
Processed approximately 10,000,000 rows...
Processed approximately 12,500,000 rows...
Processed approximately 15,000,000 rows...
Processed approximately 17,500,000 rows...
Processed approximately 20,000,000 rows...
Processed approximately 22,500,000 rows...
Processed approximately 25,000,000 rows...
Processed approximately 27,500,000 rows...

HTTP processing completed.
Users found: 1000

In [31]:
http_features_df = pd.DataFrame({
    "user": list(http_request_count.keys()),

    "http_request_count": [
        http_request_count[user]
        for user in http_request_count
    ],

    "unique_http_pc_count": [
        len(http_pcs[user])
        for user in http_request_count
    ],

    "unique_domain_count": [
        len(http_domains[user])
        for user in http_request_count
    ]
})

display(http_features_df.head(10))

print("Shape:", http_features_df.shape)

      user  http_request_count  unique_http_pc_count  unique_domain_count
0  AJR0319               72252                     1                  153
1  RZC0746               77760                     1                  167
2  ATE0869               74205                     1                  222
3  MSS0001              138000                     1                  196
4  NWK0215               63492                     1                  209
5  DLM0051               82840                     1                  215
6  KBP0008              103800                     1                  222
7  HPH0075               72720                     1                  188
8  HSB0196               57000                     1                  124
9  JCR0172               65934                     1                  148

Shape: (1000, 4)

In [32]:
print(
    "Aggregated HTTP requests:",
    http_features_df["http_request_count"].sum()
)

print(
    "Expected HTTP rows:",
    28_434_423
)

Aggregated HTTP requests: 28434423
Expected HTTP rows: 28434423

In [33]:
# ============================================================
# DEVICE FEATURE ENGINEERING
# ============================================================

from collections import defaultdict

device_activity_count = defaultdict(int)
device_connect_count = defaultdict(int)
device_disconnect_count = defaultdict(int)
device_pcs = defaultdict(set)

device_file = DATASET_PATH / "device.csv"

for chunk in pd.read_csv(
    device_file,
    chunksize=100_000,
    usecols=["user", "pc", "activity"]
):

    chunk = chunk.dropna(subset=["user"])
    chunk["user"] = chunk["user"].astype(str)

    # --------------------------------------------------------
    # Total device activity
    # --------------------------------------------------------
    counts = chunk["user"].value_counts()

    for user, count in counts.items():
        device_activity_count[user] += int(count)

    # --------------------------------------------------------
    # Connect / Disconnect
    # --------------------------------------------------------
    connect_counts = (
        chunk.loc[
            chunk["activity"].eq("Connect"),
            "user"
        ].value_counts()
    )

    disconnect_counts = (
        chunk.loc[
            chunk["activity"].eq("Disconnect"),
            "user"
        ].value_counts()
    )

    for user, count in connect_counts.items():
        device_connect_count[user] += int(count)

    for user, count in disconnect_counts.items():
        device_disconnect_count[user] += int(count)

    # --------------------------------------------------------
    # Unique PCs
    # --------------------------------------------------------
    pc_rows = chunk.dropna(subset=["pc"])

    for user, pc in zip(
        pc_rows["user"],
        pc_rows["pc"]
    ):
        device_pcs[user].add(str(pc))

print("Device processing completed.")
print("Users found:", len(device_activity_count))

Device processing completed.
Users found: 265

In [34]:
device_features_df = pd.DataFrame({
    "user": list(device_activity_count.keys()),

    "device_activity_count": [
        device_activity_count[user]
        for user in device_activity_count
    ],

    "device_connect_count": [
        device_connect_count[user]
        for user in device_activity_count
    ],

    "device_disconnect_count": [
        device_disconnect_count[user]
        for user in device_activity_count
    ],

    "unique_device_pc_count": [
        len(device_pcs[user])
        for user in device_activity_count
    ]
})

display(device_features_df.head(10))

print("Shape:", device_features_df.shape)

,user,device_activity_count,device_connect_count,device_disconnect_count,unique_device_pc_count
0,BSS0369,5472,2740,2732,489
1,AJF0370,8502,4261,4241,642
2,MPM0220,4978,2494,2484,440
3,LBH0942,7785,3903,3882,1
4,IBB0359,7852,3935,3917,580
5,OBH0499,7395,3706,3689,1
6,HSB0196,7595,3805,3790,1
7,DLM0051,7533,3775,3758,1
8,KKW0879,6501,3257,3244,1
9,IIW0249,6735,3375,3360,1

Shape: (265, 5)

In [35]:
print(
    "Aggregated device activity:",
    device_features_df["device_activity_count"].sum()
)

print(
    "Expected device rows:",
    405_380
)

print("\nActivity totals:")
print(
    "Connect:",
    device_features_df["device_connect_count"].sum()
)

print(
    "Disconnect:",
    device_features_df["device_disconnect_count"].sum()
)

Aggregated device activity: 405380
Expected device rows: 405380

Activity totals:
Connect: 203339
Disconnect: 202041

In [36]:
psychometric_df = pd.read_csv(
    DATASET_PATH / "psychometric.csv"
)

print("Shape:", psychometric_df.shape)

print("\nColumns:")
print(psychometric_df.columns.tolist())

display(psychometric_df.head())

Shape: (1000, 7)

Columns:
['employee_name', 'user_id', 'O', 'C', 'E', 'A', 'N']

             employee_name  user_id   O   C   E   A   N
0         Calvin Edan Love  CEL0561  40  39  36  19  40
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25

In [37]:
print("Missing values:")
print(psychometric_df.isna().sum())

print("\nDuplicate user IDs:")
print(
    psychometric_df["user_id"].duplicated().sum()
)

Missing values:
employee_name    0
user_id          0
O                0
C                0
E                0
A                0
N                0
dtype: int64

Duplicate user IDs:
0

In [38]:
print("Psychometric shape:", psychometric_df.shape)

print("\nPsychometric columns:")
print(psychometric_df.columns.tolist())

print("\nFirst 5 rows:")
display(psychometric_df.head())

print("\nMissing values:")
print(psychometric_df.isna().sum())

print("\nDuplicate user IDs:")
print(psychometric_df["user_id"].duplicated().sum())

Psychometric shape: (1000, 7)

Psychometric columns:
['employee_name', 'user_id', 'O', 'C', 'E', 'A', 'N']

First 5 rows:

             employee_name  user_id   O   C   E   A   N
0         Calvin Edan Love  CEL0561  40  39  36  19  40
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25

Missing values:
employee_name    0
user_id          0
O                0
C                0
E                0
A                0
N                0
dtype: int64

Duplicate user IDs:
0

In [39]:
# ============================================================
# MASTER FEATURE DATASET
# ============================================================

# Start with all users from psychometric data
master_features_df = psychometric_df.copy()

# Rename psychometric user_id to user
master_features_df = master_features_df.rename(
    columns={"user_id": "user"}
)

# ------------------------------------------------------------
# Merge Logon features
# ------------------------------------------------------------

master_features_df = master_features_df.merge(
    logon_features_df.reset_index(),
    on="user",
    how="left"
)

# ------------------------------------------------------------
# Merge Email features
# ------------------------------------------------------------

master_features_df = master_features_df.merge(
    email_features_df,
    on="user",
    how="left"
)

# ------------------------------------------------------------
# Merge File features
# ------------------------------------------------------------

master_features_df = master_features_df.merge(
    file_features_df,
    on="user",
    how="left"
)

# ------------------------------------------------------------
# Merge HTTP features
# ------------------------------------------------------------

master_features_df = master_features_df.merge(
    http_features_df,
    on="user",
    how="left"
)

# ------------------------------------------------------------
# Merge Device features
# ------------------------------------------------------------

master_features_df = master_features_df.merge(
    device_features_df,
    on="user",
    how="left"
)

print("Master feature dataset created.")
print("Shape:", master_features_df.shape)

display(master_features_df.head())

Master feature dataset created.
Shape: (1000, 27)

,employee_name,user,O,C,E,A,N,logon_count,logoff_count,after_hours_logon_count,...,file_activity_count,unique_files,unique_file_pcs,http_request_count,unique_http_pc_count,unique_domain_count,device_activity_count,device_connect_count,device_disconnect_count,unique_device_pc_count
0,Calvin Edan Love,CEL0561,40,39,36,19,40,615,346,0,...,NaN,NaN,NaN,32775,1,213,NaN,NaN,NaN,NaN
1,Christine Reagan Deleon,CRD0624,26,22,17,39,32,50,50,22,...,NaN,NaN,NaN,7290,1,131,NaN,NaN,NaN,NaN
2,Jade Felicia Caldwell,JFC0557,22,16,23,40,33,615,346,0,...,2839.0,2839.0,1.0,32870,1,107,2785.0,1399.0,1386.0,1.0
3,Aquila Stewart Dejesus,ASD0577,40,48,36,14,37,346,346,0,...,NaN,NaN,NaN,3450,1,182,NaN,NaN,NaN,NaN
4,Micah Abdul Rojas,MAR0955,36,44,23,44,25,302,302,302,...,69.0,69.0,1.0,2963,1,141,42.0,21.0,21.0,1.0

In [40]:
# Activity features that should be zero when
# the user has no recorded activity in that source.

activity_features = [
    "logon_count",
    "logoff_count",
    "after_hours_logon_count",
    "after_hours_logoff_count",
    "unique_pc_count",

    "email_count",
    "emails_with_attachments",
    "total_attachments",
    "total_email_size",
    "unique_recipients",

    "file_activity_count",
    "unique_files",
    "unique_file_pcs",

    "http_request_count",
    "unique_http_pc_count",
    "unique_domain_count",

    "device_activity_count",
    "device_connect_count",
    "device_disconnect_count",
    "unique_device_pc_count"
]

for column in activity_features:
    if column in master_features_df.columns:
        master_features_df[column] = (
            master_features_df[column]
            .fillna(0)
        )

print("Missing activity values filled with 0.")

Missing activity values filled with 0.

In [41]:
print("Shape:", master_features_df.shape)

print("\nTotal missing values:")
print(
    master_features_df.isna().sum()
)

print("\nDuplicate users:")
print(
    master_features_df["user"].duplicated().sum()
)

Shape: (1000, 27)

Total missing values:
employee_name               0
user                        0
O                           0
C                           0
E                           0
A                           0
N                           0
logon_count                 0
logoff_count                0
after_hours_logon_count     0
after_hours_logoff_count    0
unique_pc_count             0
email_count                 0
emails_with_attachments     0
total_attachments           0
total_email_size            0
unique_recipients           0
file_activity_count         0
unique_files                0
unique_file_pcs             0
http_request_count          0
unique_http_pc_count        0
unique_domain_count         0
device_activity_count       0
device_connect_count        0
device_disconnect_count     0
unique_device_pc_count      0
dtype: int64

Duplicate users:
0

In [42]:
print("Master dataset shape:", master_features_df.shape)

print("\nDuplicate users:")
print(master_features_df["user"].duplicated().sum())

print("\nMissing values:")
print(master_features_df.isna().sum())

Master dataset shape: (1000, 27)

Duplicate users:
0

Missing values:
employee_name               0
user                        0
O                           0
C                           0
E                           0
A                           0
N                           0
logon_count                 0
logoff_count                0
after_hours_logon_count     0
after_hours_logoff_count    0
unique_pc_count             0
email_count                 0
emails_with_attachments     0
total_attachments           0
total_email_size            0
unique_recipients           0
file_activity_count         0
unique_files                0
unique_file_pcs             0
http_request_count          0
unique_http_pc_count        0
unique_domain_count         0
device_activity_count       0
device_connect_count        0
device_disconnect_count     0
unique_device_pc_count      0
dtype: int64

In [43]:
from pathlib import Path

FEATURE_DIR = Path("ml/features")
FEATURE_DIR.mkdir(parents=True, exist_ok=True)

feature_file = FEATURE_DIR / "cert_user_features.csv"

master_features_df.to_csv(
    feature_file,
    index=False
)

print("Feature dataset saved to:")
print(feature_file.resolve())

print("Rows:", len(master_features_df))
print("Columns:", len(master_features_df.columns))

Feature dataset saved to:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\features\cert_user_features.csv
Rows: 1000
Columns: 27

In [44]:
display(
    master_features_df.describe().T
)

,count,mean,std,min,25%,50%,75%,max
O,1000.0,3.317300e+01,1.064201e+01,10.0,23.00,36.0,4.200000e+01,50.0
C,1000.0,3.065300e+01,1.129151e+01,10.0,20.00,33.0,4.000000e+01,50.0
E,1000.0,2.919700e+01,1.095647e+01,10.0,19.00,28.0,3.900000e+01,50.0
A,1000.0,2.882100e+01,1.117084e+01,10.0,19.00,27.0,3.900000e+01,50.0
N,1000.0,2.960800e+01,4.938494e+00,14.0,26.00,29.0,3.300000e+01,49.0
logon_count,1000.0,4.705910e+02,2.501300e+02,29.0,346.00,346.0,6.200000e+02,1777.0
logoff_count,1000.0,3.842680e+02,1.913786e+02,27.0,346.00,346.0,3.742500e+02,1735.0
after_hours_logon_count,1000.0,1.811100e+02,2.092929e+02,0.0,0.00,157.0,3.460000e+02,1269.0
after_hours_logoff_count,1000.0,1.626920e+02,1.990237e+02,0.0,0.00,46.0,3.460000e+02,1063.0
unique_pc_count,1000.0,5.780000e+00,2.124408e+01,1.0,1.00,1.0,2.000000e+00,145.0
email_count,1000.0,2.629979e+03,1.830294e+03,34.0,1001.00,3002.0,3.693250e+03,12034.0
emails_with_attachments,1000.0,5.632960e+02,5.964073e+02,0.0,67.00,387.0,9.352500e+02,3659.0
total_attachments,1000.0,1.061449e+03,1.116431e+03,0.0,126.50,711.0,1.790000e+03,7372.0
total_email_size,1000.0,7.887917e+07,5.488427e+07,1062576.0,29961671.00,89923538.0,1.110407e+08,361399921.0
unique_recipients,1000.0,1.280075e+03,8.243672e+02,42.0,621.75,1350.5,1.708000e+03,4022.0
file_activity_count,1000.0,4.455810e+02,1.461942e+03,0.0,0.00,0.0,1.025000e+01,11627.0
unique_files,1000.0,4.455810e+02,1.461942e+03,0.0,0.00,0.0,1.025000e+01,11627.0
unique_file_pcs,1000.0,3.334000e+00,3.175227e+01,0.0,0.00,0.0,1.000000e+00,417.0
http_request_count,1000.0,2.843442e+04,2.022201e+04,350.0,10034.00,32870.0,3.944400e+04,138000.0
unique_http_pc_count,1000.0,1.000000e+00,0.000000e+00,1.0,1.00,1.0,1.000000e+00,1.0
unique_domain_count,1000.0,1.479290e+02,4.722495e+01,40.0,111.00,145.0,1.800000e+02,271.0
device_activity_count,1000.0,4.053800e+02,1.234482e+03,0.0,0.00,0.0,1.400000e+01,8502.0
device_connect_count,1000.0,2.033390e+02,6.187744e+02,0.0,0.00,0.0,7.000000e+00,4261.0
device_disconnect_count,1000.0,2.020410e+02,6.157079e+02,0.0,0.00,0.0,7.000000e+00,4241.0
unique_device_pc_count,1000.0,5.351000e+00,5.187239e+01,0.0,0.00,0.0,1.000000e+00,642.0

In [45]:
print(master_features_df.columns.tolist())

['employee_name', 'user', 'O', 'C', 'E', 'A', 'N', 'logon_count', 'logoff_count', 'after_hours_logon_count', 'after_hours_logoff_count', 'unique_pc_count', 'email_count', 'emails_with_attachments', 'total_attachments', 'total_email_size', 'unique_recipients', 'file_activity_count', 'unique_files', 'unique_file_pcs', 'http_request_count', 'unique_http_pc_count', 'unique_domain_count', 'device_activity_count', 'device_connect_count', 'device_disconnect_count', 'unique_device_pc_count']

In [46]:
print("Files available in CERT dataset:")

for file in sorted(DATASET_PATH.iterdir()):
    print(file.name)

Files available in CERT dataset:
device.csv
email.csv
file.csv
http.csv
LDAP
license.txt
logon.csv
psychometric.csv
readme.txt

In [47]:
print("\nFiles containing possible ground-truth information:")

keywords = [
    "r5",
    "scenario",
    "answer",
    "insider",
    "malicious",
    "ground",
    "truth",
    "role"
]

for file in sorted(DATASET_PATH.iterdir()):
    name = file.name.lower()

    if any(keyword in name for keyword in keywords):
        print(file.name)

Files containing possible ground-truth information:

In [48]:
print("CERT R4.2 files:")
for file in sorted(DATASET_PATH.iterdir()):
    print("-", file.name)

CERT R4.2 files:
- device.csv
- email.csv
- file.csv
- http.csv
- LDAP
- license.txt
- logon.csv
- psychometric.csv
- readme.txt

In [49]:
# ============================================================
# ML FEATURE PREPARATION
# ============================================================

print("Master dataset shape:", master_features_df.shape)

print("\nData types:")
print(master_features_df.dtypes)

print("\nMissing values:")
print(master_features_df.isna().sum())

print("\nNumber of numeric columns:",
      master_features_df.select_dtypes(
          include="number"
      ).shape[1])

Master dataset shape: (1000, 27)

Data types:
employee_name                   str
user                            str
O                             int64
C                             int64
E                             int64
A                             int64
N                             int64
logon_count                   int64
logoff_count                  int64
after_hours_logon_count       int64
after_hours_logoff_count      int64
unique_pc_count               int64
email_count                   int64
emails_with_attachments       int64
total_attachments             int64
total_email_size              int64
unique_recipients             int64
file_activity_count         float64
unique_files                float64
unique_file_pcs             float64
http_request_count            int64
unique_http_pc_count          int64
unique_domain_count           int64
device_activity_count       float64
device_connect_count        float64
device_disconnect_count     float64
unique_device_pc_count      float64
dtype: object

Missing values:
employee_name               0
user                        0
O                           0
C                           0
E                           0
A                           0
N                           0
logon_count                 0
logoff_count                0
after_hours_logon_count     0
after_hours_logoff_count    0
unique_pc_count             0
email_count                 0
emails_with_attachments     0
total_attachments           0
total_email_size            0
unique_recipients           0
file_activity_count         0
unique_files                0
unique_file_pcs             0
http_request_count          0
unique_http_pc_count        0
unique_domain_count         0
device_activity_count       0
device_connect_count        0
device_disconnect_count     0
unique_device_pc_count      0
dtype: int64

Number of numeric columns: 25

In [50]:
# ============================================================
# ML FEATURE MATRIX
# ============================================================

# Columns that identify the employee/user.
ID_COLUMNS = [
    "employee_name",
    "user"
]

# Select only numeric behavioral/personality features.
X = master_features_df.drop(
    columns=ID_COLUMNS
).copy()

print("Feature matrix shape:", X.shape)

print("\nFeature columns:")
for column in X.columns:
    print("-", column)

Feature matrix shape: (1000, 25)

Feature columns:
- O
- C
- E
- A
- N
- logon_count
- logoff_count
- after_hours_logon_count
- after_hours_logoff_count
- unique_pc_count
- email_count
- emails_with_attachments
- total_attachments
- total_email_size
- unique_recipients
- file_activity_count
- unique_files
- unique_file_pcs
- http_request_count
- unique_http_pc_count
- unique_domain_count
- device_activity_count
- device_connect_count
- device_disconnect_count
- unique_device_pc_count

In [51]:
# Check missing values
print("Total missing values:", X.isna().sum().sum())

# Check infinite values
print(
    "Total infinite values:",
    X.isin([float("inf"), float("-inf")]).sum().sum()
)

# Check constant features
constant_features = [
    column
    for column in X.columns
    if X[column].nunique() <= 1
]

print("\nConstant features:")
print(constant_features)

Total missing values: 0
Total infinite values: 0

Constant features:
['unique_http_pc_count']

In [52]:
# ============================================================
# REMOVE CONSTANT FEATURES FROM ML INPUT
# ============================================================

constant_features = [
    column
    for column in X.columns
    if X[column].nunique() <= 1
]

print("Constant features:", constant_features)

X_model = X.drop(
    columns=constant_features
).copy()

print("\nOriginal feature count:", X.shape[1])
print("ML feature count:", X_model.shape[1])
print("Removed:", constant_features)

Constant features: ['unique_http_pc_count']

Original feature count: 25
ML feature count: 24
Removed: ['unique_http_pc_count']

In [53]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_model)

print("Scaled feature matrix shape:", X_scaled.shape)

Scaled feature matrix shape: (1000, 24)

In [54]:
# ============================================================
# ISOLATION FOREST - INSIDER THREAT ANOMALY DETECTION
# ============================================================

from sklearn.ensemble import IsolationForest

model = IsolationForest(
    n_estimators=300,
    contamination=0.05,
    random_state=42,
    n_jobs=-1
)

model.fit(X_scaled)

print("Isolation Forest training completed.")
print("Number of trees:", model.n_estimators)
print("Contamination:", model.contamination)

Isolation Forest training completed.
Number of trees: 300
Contamination: 0.05

In [55]:
# ============================================================
# GENERATE ANOMALY SCORES
# ============================================================

raw_scores = model.decision_function(X_scaled)

predictions = model.predict(X_scaled)

print("Anomaly scores generated.")

print("\nPrediction counts:")
print(pd.Series(predictions).value_counts())

Anomaly scores generated.

Prediction counts:
 1    950
-1     50
Name: count, dtype: int64

In [56]:
print("Minimum score:", raw_scores.min())
print("Maximum score:", raw_scores.max())
print("Mean score:", raw_scores.mean())

Minimum score: -0.19560695844399012
Maximum score: 0.19437729431085726
Mean score: 0.12707387147972263

In [57]:
# ============================================================
# CONVERT ANOMALY SCORE → RISK SCORE
# ============================================================

anomaly_strength = -raw_scores

min_score = anomaly_strength.min()
max_score = anomaly_strength.max()

if max_score == min_score:
    risk_scores = pd.Series(
        0.0,
        index=master_features_df.index
    )
else:
    risk_scores = pd.Series(
        (
            (anomaly_strength - min_score)
            / (max_score - min_score)
            * 100
        ),
        index=master_features_df.index
    )

risk_scores = risk_scores.round(2)

print("Risk score generated.")

print("\nRisk score statistics:")
print(risk_scores.describe())

Risk score generated.

Risk score statistics:
count    1000.000000
mean       17.258020
std        15.336294
min         0.000000
25%         6.952500
50%        11.860000
75%        22.890000
max       100.000000
dtype: float64

In [58]:
# ============================================================
# RISK LEVEL
# ============================================================

def get_risk_level(score):
    if score < 25:
        return "Low"
    elif score < 50:
        return "Medium"
    elif score < 75:
        return "High"
    else:
        return "Critical"


risk_levels = risk_scores.apply(get_risk_level)

print(risk_levels.value_counts())

Low         783
Medium      167
High         40
Critical     10
Name: count, dtype: int64

In [59]:
# ============================================================
# FINAL RISK RESULTS
# ============================================================

risk_results_df = master_features_df[
    ["employee_name", "user"]
].copy()

risk_results_df["anomaly_score"] = raw_scores
risk_results_df["risk_score"] = risk_scores
risk_results_df["risk_level"] = risk_levels
risk_results_df["is_anomaly"] = (
    predictions == -1
)

display(
    risk_results_df
    .sort_values(
        "risk_score",
        ascending=False
    )
    .head(20)
)

,employee_name,user,anomaly_score,risk_score,risk_level,is_anomaly
150,Arthur John Floyd,AJF0370,-0.195607,100.00,Critical,True
567,Ira Brendan Ball,IBB0359,-0.158683,90.53,Critical,True
727,Hayes Drake Stephenson,HDS0367,-0.147069,87.55,Critical,True
537,Byron Armand Livingston,BAL0044,-0.141958,86.24,Critical,True
85,Emerald Imani Schmidt,EIS0041,-0.141670,86.17,Critical,True
497,Meghan Phoebe Macias,MPM0220,-0.132444,83.80,Critical,True
844,Declan Lester Moss,DLM0051,-0.132232,83.75,Critical,True
898,Brenden Samuel Shaffer,BSS0369,-0.123005,81.38,Critical,True
777,Harper Price Harris,HPH0075,-0.106140,77.06,Critical,True
856,Hadley Sonya Bowen,HSB0196,-0.102441,76.11,Critical,True
169,Halla Cathleen Simmons,HCS0003,-0.093858,73.91,High,True
852,Ayanna Vivian Murray,AVM0947,-0.081274,70.68,High,True
577,Mariko Olga Snyder,MOS0047,-0.071374,68.14,High,True
229,Lyle Brady Hayes,LBH0942,-0.066076,66.79,High,True
750,Cyrus Connor Atkinson,CCA0046,-0.064832,66.47,High,True
181,Orson Barrett Houston,OBH0499,-0.064113,66.28,High,True
612,Nichole Azalia Frye,NAF0326,-0.055847,64.16,High,True
107,Beck John Peters,BJP0134,-0.054509,63.82,High,True
981,Bell Jorden Martinez,BJM0111,-0.053318,63.51,High,True
144,Zenia Kiona Stevenson,ZKS0899,-0.053084,63.45,High,True

In [60]:
from pathlib import Path

MODEL_DIR = Path("ml/models")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

print("Model directory:")
print(MODEL_DIR.resolve())

Model directory:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models

In [61]:
import joblib

model_path = MODEL_DIR / "isolation_forest.pkl"
scaler_path = MODEL_DIR / "scaler.pkl"

joblib.dump(model, model_path)
joblib.dump(scaler, scaler_path)

print("Isolation Forest saved:")
print(model_path.resolve())

print("\nScaler saved:")
print(scaler_path.resolve())

Isolation Forest saved:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\isolation_forest.pkl

Scaler saved:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\scaler.pkl

In [62]:
feature_columns_path = MODEL_DIR / "feature_columns.txt"

with open(
    feature_columns_path,
    "w",
    encoding="utf-8"
) as f:
    for column in X_model.columns:
        f.write(column + "\n")

print("Feature columns saved:")
print(feature_columns_path.resolve())

print("\nNumber of features:", len(X_model.columns))

Feature columns saved:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\feature_columns.txt

Number of features: 24

In [63]:
risk_results_path = MODEL_DIR / "risk_results.csv"

risk_results_df.to_csv(
    risk_results_path,
    index=False
)

print("Risk results saved:")
print(risk_results_path.resolve())

print("\nRows saved:", len(risk_results_df))

Risk results saved:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\risk_results.csv

Rows saved: 1000

In [64]:
print("Model files:")
for file in MODEL_DIR.iterdir():
    print(
        f"{file.name} | "
        f"{file.stat().st_size:,} bytes"
    )

Model files:
feature_columns.txt | 391 bytes
isolation_forest.pkl | 3,189,897 bytes
risk_calibration.json | 213 bytes
risk_results.csv | 65,616 bytes
scaler.pkl | 1,815 bytes

In [65]:
print("Model files:")
for file in MODEL_DIR.iterdir():
    print(
        f"{file.name} | "
        f"{file.stat().st_size:,} bytes"
    )

Model files:
feature_columns.txt | 391 bytes
isolation_forest.pkl | 3,189,897 bytes
risk_calibration.json | 213 bytes
risk_results.csv | 65,616 bytes
scaler.pkl | 1,815 bytes

In [66]:
loaded_model = joblib.load(
    MODEL_DIR / "isolation_forest.pkl"
)

loaded_scaler = joblib.load(
    MODEL_DIR / "scaler.pkl"
)

print("Saved model loaded successfully.")
print("Saved scaler loaded successfully.")

print(
    "Model type:",
    type(loaded_model).__name__
)

print(
    "Scaler type:",
    type(loaded_scaler).__name__
)

Saved model loaded successfully.
Saved scaler loaded successfully.
Model type: IsolationForest
Scaler type: StandardScaler

In [67]:
loaded_scaled_data = loaded_scaler.transform(X_model)

loaded_predictions = loaded_model.predict(
    loaded_scaled_data
)

print(
    "Predictions identical:",
    (loaded_predictions == predictions).all()
)

Predictions identical: True

In [68]:
# ============================================================
# SAVE RISK SCORE CALIBRATION
# ============================================================

import json

calibration = {
    "min_anomaly_strength": float(min_score),
    "max_anomaly_strength": float(max_score),
    "risk_thresholds": {
        "low_max": 24,
        "medium_max": 49,
        "high_max": 74
    }
}

calibration_path = MODEL_DIR / "risk_calibration.json"

with open(
    calibration_path,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        calibration,
        f,
        indent=4
    )

print("Risk calibration saved:")
print(calibration_path.resolve())

print("\nCalibration:")
print(json.dumps(calibration, indent=4))

Risk calibration saved:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\risk_calibration.json

Calibration:
{
    "min_anomaly_strength": -0.19437729431085726,
    "max_anomaly_strength": 0.19560695844399012,
    "risk_thresholds": {
        "low_max": 24,
        "medium_max": 49,
        "high_max": 74
    }
}

In [69]:
print("min_anomaly_strength =", min_score)
print("max_anomaly_strength =", max_score)

min_anomaly_strength = -0.19437729431085726
max_anomaly_strength = 0.19560695844399012

In [70]:
import json

calibration = {
    "min_anomaly_strength": float(min_score),
    "max_anomaly_strength": float(max_score),
    "risk_thresholds": {
        "low_max": 24,
        "medium_max": 49,
        "high_max": 74
    }
}

calibration_path = MODEL_DIR / "risk_calibration.json"

with open(
    calibration_path,
    "w",
    encoding="utf-8"
) as f:
    json.dump(calibration, f, indent=4)

print("Risk calibration saved successfully:")
print(calibration_path.resolve())

Risk calibration saved successfully:
C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\risk_calibration.json

In [71]:
print(calibration)

{'min_anomaly_strength': -0.19437729431085726, 'max_anomaly_strength': 0.19560695844399012, 'risk_thresholds': {'low_max': 24, 'medium_max': 49, 'high_max': 74}}

In [72]:
print("Exact ML feature columns:")
for i, column in enumerate(X_model.columns, start=1):
    print(f"{i}. {column}")

Exact ML feature columns:
1. O
2. C
3. E
4. A
5. N
6. logon_count
7. logoff_count
8. after_hours_logon_count
9. after_hours_logoff_count
10. unique_pc_count
11. email_count
12. emails_with_attachments
13. total_attachments
14. total_email_size
15. unique_recipients
16. file_activity_count
17. unique_files
18. unique_file_pcs
19. http_request_count
20. unique_domain_count
21. device_activity_count
22. device_connect_count
23. device_disconnect_count
24. unique_device_pc_count

In [73]:
from pathlib import Path

print("Notebook working directory:")
print(Path.cwd())

Notebook working directory:
c:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks

In [74]:
from pathlib import Path

print("Searching for saved ML files...")

project_root = Path(
    r"C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System"
)

files_to_find = [
    "isolation_forest.pkl",
    "scaler.pkl",
    "feature_columns.txt",
    "risk_results.csv",
    "risk_calibration.json",
]

for filename in files_to_find:
    matches = list(project_root.rglob(filename))

    print(f"\n{filename}:")
    
    if matches:
        for path in matches:
            print("FOUND:", path)
    else:
        print("NOT FOUND")

Searching for saved ML files...

isolation_forest.pkl:
FOUND: C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\isolation_forest.pkl

scaler.pkl:
FOUND: C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\scaler.pkl

feature_columns.txt:
FOUND: C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\feature_columns.txt

risk_results.csv:
FOUND: C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\risk_results.csv

risk_calibration.json:
FOUND: C:\Users\nulim\OneDrive\Desktop\Insider-Threat-Behavioral-Intelligence-System\backend\ml\notebooks\ml\models\risk_calibration.json